apiVersion: v1
kind: Service
metadata:
  name: hello-arc
  namespace: hello-arc
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: hello-arc
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-arc
  namespace: hello-arc
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hello-arc
  template:
    metadata:
      labels:
        app: hello-arc
    spec:
      containers:
      - name: hello-arc
        image: mcr.microsoft.com/jumpstart/arcbox/hello_arc:1.0.0
        ports:
        - containerPort: 8080
        env:
        - name: MESSAGE
          value: Welcome to Ignite 2023!
