# Create Contoso Supermarket Service
apiVersion: v1
kind: Service
metadata:
  name: contosopos
  namespace: contosopos
  labels:
    app: contosopos
spec:
  selector:
    app: contosopos
  ports:
  - name: http
    port: 80
    targetPort: 5000
  type: ClusterIP
---  
# Create Contoso Supermarket Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: contosopos
  namespace: contosopos
  labels:
    app: contosopos
spec:
  replicas: 1
  selector:
    matchLabels:
      app: contosopos
  template:
    metadata:
      labels:
        app: contosopos
    spec:
      containers:
        - name: contosopos
          image: azurearcjumpstart.azurecr.io/contoso-supermarket:latest
          env:
            - name: SQL_HOST
              value: ""
            - name: SQL_USERNAME
              value: ""
            - name: SQL_PASSWORD
              value: ""
            - name: SQL_DATABASE
              value: ""
            - name: HEAD_TITLE
              value : "Contoso Supermarket"
            - name: CAMERAS_ENABLED
              value: "False"
            - name: CAMERAS_BASEURL
              value: ""
            - name: NEW_CATEGORY
              value: "True"
          ports:
            - containerPort: 5000
        - name: contosocameras
          image: azurearcjumpstart.azurecr.io/contoso-supermarket-cameras:latest
