---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: contoso-mqtt-pub-client
  namespace: contoso
  labels:
    app: mqtt-pub-client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mqtt-pub-client
  template: 
    metadata:
      labels:
        app: mqtt-pub-client
    spec:
      containers:
      - name: publisher
        image: containerregistryswapnil.azurecr.io/publisher:v1
      imagePullSecrets:
      - name: acr-secret-edgezone

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: contoso-webapp
  namespace: contoso
  labels: 
    app: webapp
spec:
  replicas: 1
  selector: 
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers: 
      - name: webapp
        image: containerregistryswapnil.azurecr.io/flaskapp-mqtt:v1
        ports:
        - containerPort: 5000
      imagePullSecrets:
      - name: acr-secret-edgezone

---
apiVersion: v1
kind: Service
metadata:
  name: contoso-webapp-service
  namespace: contoso
spec:
  type: LoadBalancer
  selector:
    app: webapp
  ports:
  - port: 5000
    targetPort: 5000
    protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: contoso-video-ai-inferencing
  namespace: contoso
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: contoso-pos
  namespace: contoso
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
